require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product.model');

const MONGODB_URI = process.env.MONGODB_URI;

const PRODUCTS_50 = [
  // Hair Care (1-10)
  {
    id: 'prod_1',
    title: 'Kuntal Care Hair Oil',
    subtitle: 'Revitalizing Herbal Hair Tonic',
    category: 'Hair Care',
    size: '200 ml',
    price: 649,
    originalPrice: 799,
    rating: 4.9,
    reviewCount: 420,
    badge: 'BESTSELLER',
    inStock: true,
    stockQuantity: 120,
    description: 'Enriched with Bhringraj, Neem & Amla to control hair fall & nourish scalp deep into roots.',
    ingredients: ['Bhringraj', 'Neem', 'Amla', 'Sesame Oil', 'Jatamansi'],
  },
  {
    id: 'prod_2',
    title: 'Kuntal Care Herbal Hair Spa',
    subtitle: 'Deep Conditioning Scalp Mask',
    category: 'Hair Care',
    size: '200 g',
    price: 799,
    originalPrice: 999,
    rating: 4.8,
    reviewCount: 310,
    badge: 'POPULAR',
    inStock: true,
    stockQuantity: 85,
    description: 'Ayurvedic hair spa formulation with Shikakai, Reetha & Hibiscus for smooth glossy hair.',
    ingredients: ['Shikakai', 'Reetha', 'Hibiscus', 'Bhringraj', 'Aloe Vera'],
  },
  {
    id: 'prod_3',
    title: 'Kuntal Care Herbal Shampoo',
    subtitle: 'Sulphate Free Daily Cleanser',
    category: 'Hair Care',
    size: '300 ml',
    price: 549,
    originalPrice: 699,
    rating: 4.7,
    reviewCount: 280,
    badge: 'ORGANIC',
    inStock: true,
    stockQuantity: 140,
    description: 'Gentle Ayurvedic cleanser with Soapnut & Reetha that purifies scalp without stripping oils.',
    ingredients: ['Reetha', 'Shikakai', 'Amla', 'Neem Leaf'],
  },
  {
    id: 'prod_4',
    title: 'Jatamansi Scalp Vitality Tonic',
    subtitle: 'Anti-Dandruff & Root Booster',
    category: 'Hair Care',
    size: '100 ml',
    price: 699,
    originalPrice: 849,
    rating: 4.8,
    reviewCount: 195,
    badge: 'NEW',
    inStock: true,
    stockQuantity: 60,
    description: 'Concentrated herbal extract of Jatamansi & Nagarmotha for scalp cooling & itch relief.',
    ingredients: ['Jatamansi', 'Nagarmotha', 'Camphor', 'Tea Tree Oil'],
  },
  {
    id: 'prod_5',
    title: 'Brahmi & Bhringraj Hair Growth Serum',
    subtitle: 'Non-Greasy Botanical Serum',
    category: 'Hair Care',
    size: '50 ml',
    price: 899,
    originalPrice: 1099,
    rating: 4.9,
    reviewCount: 350,
    badge: 'HIGHLY RATED',
    inStock: true,
    stockQuantity: 75,
    description: 'Lightweight overnight serum designed to stimulate dormant hair follicles.',
    ingredients: ['Brahmi', 'Bhringraj', 'Rosemary Oil', 'Redensyl', 'Onion Seed'],
  },
  {
    id: 'prod_6',
    title: 'Neem & Karanja Scalp Therapy Pack',
    subtitle: 'Purifying Herbal Hair Cleanser',
    category: 'Hair Care',
    size: '150 g',
    price: 499,
    originalPrice: 599,
    rating: 4.6,
    reviewCount: 140,
    badge: 'HERBAL',
    inStock: true,
    stockQuantity: 90,
    description: 'Traditional churna hair mask for flaky scalp & fungal protection.',
    ingredients: ['Neem', 'Karanja', 'Tulsi', 'Methi Seed'],
  },
  {
    id: 'prod_7',
    title: 'Hibiscus & Rose Hair Softening Oil',
    subtitle: 'Nourishing Pre-Wash Elixir',
    category: 'Hair Care',
    size: '200 ml',
    price: 599,
    originalPrice: 749,
    rating: 4.8,
    reviewCount: 210,
    badge: 'TOP CHOICE',
    inStock: true,
    stockQuantity: 110,
    description: 'Cold-pressed coconut oil infused with fresh Hibiscus flowers & Kashmiri Rose petals.',
    ingredients: ['Hibiscus Petals', 'Damask Rose', 'Coconut Oil', 'Almond Oil'],
  },
  {
    id: 'prod_8',
    title: 'Methi & Onion Anti Hair Fall Oil',
    subtitle: 'Traditional Density Restorer',
    category: 'Hair Care',
    size: '200 ml',
    price: 629,
    originalPrice: 799,
    rating: 4.7,
    reviewCount: 380,
    badge: 'BESTSELLER',
    inStock: true,
    stockQuantity: 130,
    description: 'Ayurvedic formulation packed with sulfur-rich Onion seed extract & Fenugreek.',
    ingredients: ['Onion Seed Oil', 'Fenugreek (Methi)', 'Black Seed Oil', 'Sesame'],
  },
  {
    id: 'prod_9',
    title: 'Amla & Curry Leaf Hair Color Lock',
    subtitle: 'Premature Graying Protection',
    category: 'Hair Care',
    size: '150 ml',
    price: 679,
    originalPrice: 849,
    rating: 4.8,
    reviewCount: 160,
    badge: 'NEW',
    inStock: true,
    stockQuantity: 70,
    description: 'Rich in natural antioxidants & Vitamin C to preserve natural hair melanin.',
    ingredients: ['Fresh Amla', 'Curry Leaves', 'Sesame Oil', 'Castor Oil'],
  },
  {
    id: 'prod_10',
    title: 'Aloe Vera & Coconut Hydrating Hair Gel',
    subtitle: 'Natural Styling & Frizz Control',
    category: 'Hair Care',
    size: '100 g',
    price: 449,
    originalPrice: 549,
    rating: 4.5,
    reviewCount: 125,
    badge: 'NATURAL',
    inStock: true,
    stockQuantity: 100,
    description: 'Zero chemical styling gel with pure Aloe Vera leaf juice for flexible hold.',
    ingredients: ['Aloe Vera Juice', 'Coconut Milk Extract', 'Vegetable Glycerin'],
  },

  // Skin Care (11-20)
  {
    id: 'prod_11',
    title: 'Kumkumadi Skin Radiance Oil',
    subtitle: '100% Pure Saffron Face Oil',
    category: 'Skin Care',
    size: '30 ml',
    price: 1199,
    originalPrice: 1499,
    rating: 4.9,
    reviewCount: 650,
    badge: 'PREMIUM',
    inStock: true,
    stockQuantity: 65,
    description: 'Kashmiri Kesar & Chandan formulation for natural glowing skin & pigmentation reduction.',
    ingredients: ['Kashmiri Saffron', 'Sandalwood', 'Manjistha', 'Lotus Extract', 'Vetiver'],
  },
  {
    id: 'prod_12',
    title: 'Chandan & Haldi Brightening Face Wash',
    subtitle: 'Soap-Free Facial Cleanser',
    category: 'Skin Care',
    size: '150 ml',
    price: 449,
    originalPrice: 549,
    rating: 4.7,
    reviewCount: 410,
    badge: 'BESTSELLER',
    inStock: true,
    stockQuantity: 160,
    description: 'Gentle daily cleanser with Sandalwood & Wild Turmeric for clear complexion.',
    ingredients: ['Sandalwood Oil', 'Wild Turmeric', 'Aloe Vera', 'Honey'],
  },
  {
    id: 'prod_13',
    title: 'Kesar & Niacinamide Radiance Cream',
    subtitle: 'Day & Night Moisture Boost',
    category: 'Skin Care',
    size: '50 g',
    price: 799,
    originalPrice: 999,
    rating: 4.8,
    reviewCount: 290,
    badge: 'TOP RATED',
    inStock: true,
    stockQuantity: 90,
    description: 'Ayurvedic blend of Saffron extract with botanical hydrates for soft youthful texture.',
    ingredients: ['Saffron Extract', 'Shea Butter', 'Liquorice Root', 'Gotu Kola'],
  },
  {
    id: 'prod_14',
    title: 'Aloe Vera & Neem Anti Acne Gel',
    subtitle: 'Pore Clarifying Treatment',
    category: 'Skin Care',
    size: '100 g',
    price: 399,
    originalPrice: 499,
    rating: 4.6,
    reviewCount: 230,
    badge: 'ESSENTIAL',
    inStock: true,
    stockQuantity: 150,
    description: 'Cooling gel formula to soothe breakouts, reduce redness & regulate sebum.',
    ingredients: ['Organic Aloe Vera', 'Neem Extract', 'Tea Tree', 'Tulsi'],
  },
  {
    id: 'prod_15',
    title: 'Damask Rose & Vetiver Facial Toner',
    subtitle: 'Steam Distilled Floral Mist',
    category: 'Skin Care',
    size: '200 ml',
    price: 499,
    originalPrice: 599,
    rating: 4.9,
    reviewCount: 520,
    badge: 'POPULAR',
    inStock: true,
    stockQuantity: 115,
    description: 'Pure Kannauj Rose water mist that tightens open pores & balances skin pH.',
    ingredients: ['Pure Damask Rose Water', 'Vetiver Root Extract'],
  },
  {
    id: 'prod_16',
    title: 'Haldi & Chandan Ubtan Face Mask',
    subtitle: 'Exfoliating Herbal Scrub',
    category: 'Skin Care',
    size: '100 g',
    price: 549,
    originalPrice: 699,
    rating: 4.8,
    reviewCount: 340,
    badge: 'TRADITIONAL',
    inStock: true,
    stockQuantity: 95,
    description: 'Classic royal Ubtan formula with Besan, Turmeric & Rose petals for instant glow.',
    ingredients: ['Besan', 'Wild Turmeric', 'Sandalwood Powder', 'Almond Meal'],
  },
  {
    id: 'prod_17',
    title: 'Gotu Kola & Ashwagandha Eye Cream',
    subtitle: 'Dark Circle & Puffiness Repair',
    category: 'Skin Care',
    size: '25 g',
    price: 699,
    originalPrice: 849,
    rating: 4.7,
    reviewCount: 180,
    badge: 'NEW',
    inStock: true,
    stockQuantity: 70,
    description: 'Nourishing eye contour balm enriched with Centella Asiatica & Vitamin E.',
    ingredients: ['Gotu Kola', 'Ashwagandha', 'Cucumber Extract', 'Sweet Almond Oil'],
  },
  {
    id: 'prod_18',
    title: 'Nalpamaradi Body Glowing Oil',
    subtitle: 'Traditional Bridal Glow Formula',
    category: 'Skin Care',
    size: '200 ml',
    price: 749,
    originalPrice: 899,
    rating: 4.9,
    reviewCount: 460,
    badge: 'BESTSELLER',
    inStock: true,
    stockQuantity: 105,
    description: 'Sun tan removal oil infused with Turmeric, Vetiver & Banyan tree bark.',
    ingredients: ['Turmeric', 'Vetiver', 'Sesame Oil', 'Ficus Bark'],
  },
  {
    id: 'prod_19',
    title: 'Eladi Hydrating Body Lotion',
    subtitle: 'Silk Smooth Skin Moisturizer',
    category: 'Skin Care',
    size: '300 ml',
    price: 599,
    originalPrice: 749,
    rating: 4.6,
    reviewCount: 210,
    badge: 'NATURAL',
    inStock: true,
    stockQuantity: 130,
    description: 'Cardamom & Cinnamon herbal lotion that deeply quenches dry skin.',
    ingredients: ['Cardamom', 'Cinnamon', 'Kokum Butter', 'Coconut Oil'],
  },
  {
    id: 'prod_20',
    title: 'Vetiver & Neem Cleansing Bar',
    subtitle: 'Artisanal Cold Processed Soap',
    category: 'Skin Care',
    size: '125 g',
    price: 249,
    originalPrice: 299,
    rating: 4.8,
    reviewCount: 390,
    badge: 'HANDMADE',
    inStock: true,
    stockQuantity: 200,
    description: '100% natural glycerine soap with crushed Vetiver root for aromatic baths.',
    ingredients: ['Vetiver Root', 'Neem Leaf', 'Castor Oil', 'Coconut Oil'],
  },

  // Wellness Oils (21-30)
  {
    id: 'prod_21',
    title: 'Ortho Gold Joint Pain Oil',
    subtitle: 'Fast Action Muscle & Joint Relief',
    category: 'Wellness Oils',
    size: '100 ml',
    price: 549,
    originalPrice: 699,
    rating: 4.8,
    reviewCount: 540,
    badge: 'FAST RELIEF',
    inStock: true,
    stockQuantity: 140,
    description: 'Ayurvedic pain relief oil enriched with Mahanarayan & Nirgundi for joint mobility.',
    ingredients: ['Mahanarayan Oil', 'Nirgundi', 'Gandhapura', 'Eucalyptus', 'Camphor'],
  },
  {
    id: 'prod_22',
    title: 'Mahanarayan Taila Massage Oil',
    subtitle: 'Classic Vata Pacifying Formula',
    category: 'Wellness Oils',
    size: '200 ml',
    price: 649,
    originalPrice: 799,
    rating: 4.9,
    reviewCount: 370,
    badge: 'CLASSIC',
    inStock: true,
    stockQuantity: 110,
    description: 'Traditional 56-herb formulation for nerve relaxation & muscle stiffness.',
    ingredients: ['Dashamoola', 'Shatavari', 'Sesame Oil', 'Camphor'],
  },
  {
    id: 'prod_23',
    title: 'Dhanwantharam Thailam Body Oil',
    subtitle: 'Postnatal & Full Body Abhyanga',
    category: 'Wellness Oils',
    size: '200 ml',
    price: 699,
    originalPrice: 849,
    rating: 4.9,
    reviewCount: 290,
    badge: 'POPULAR',
    inStock: true,
    stockQuantity: 95,
    description: 'Restorative body massage oil crafted with Balamoola & Cow milk.',
    ingredients: ['Balamoola', 'Ashwagandha', 'Sesame Oil', 'Cow Milk'],
  },
  {
    id: 'prod_24',
    title: 'Nirgundi & Eucalyptus Back Pain Roll-On',
    subtitle: 'Instant Portable Relief Balm',
    category: 'Wellness Oils',
    size: '50 ml',
    price: 349,
    originalPrice: 429,
    rating: 4.7,
    reviewCount: 260,
    badge: 'CONVENIENT',
    inStock: true,
    stockQuantity: 175,
    description: 'Targeted roll-on application for lower back pain, neck stiffness & sprains.',
    ingredients: ['Nirgundi', 'Eucalyptus', 'Wintergreen', 'Menthol'],
  },
  {
    id: 'prod_25',
    title: 'Karpuradi Soothing Chest Rub Oil',
    subtitle: 'Cold & Congestion Ease',
    category: 'Wellness Oils',
    size: '100 ml',
    price: 399,
    originalPrice: 499,
    rating: 4.8,
    reviewCount: 310,
    badge: 'WINTER CARE',
    inStock: true,
    stockQuantity: 125,
    description: 'Aromatic Camphor & Ajwain oil to clear nasal passages & warm chest.',
    ingredients: ['Pure Camphor', 'Ajwain Oil', 'Mustard Oil', 'Eucalyptus'],
  },
  {
    id: 'prod_26',
    title: 'Bala Ashwagandha Muscle Tonic Oil',
    subtitle: 'Strength & Stamina Oil',
    category: 'Wellness Oils',
    size: '200 ml',
    price: 599,
    originalPrice: 749,
    rating: 4.8,
    reviewCount: 190,
    badge: 'ORGANIC',
    inStock: true,
    stockQuantity: 80,
    description: 'Strengthens weak muscles & promotes endurance in athletes & elders.',
    ingredients: ['Bala', 'Ashwagandha', 'Laksha', 'Sesame Oil'],
  },
  {
    id: 'prod_27',
    title: 'Anu Thailam Nasal Drops',
    subtitle: 'Nasyam Therapy for Sinus Care',
    category: 'Wellness Oils',
    size: '20 ml',
    price: 299,
    originalPrice: 349,
    rating: 4.9,
    reviewCount: 480,
    badge: 'BESTSELLER',
    inStock: true,
    stockQuantity: 210,
    description: 'Classical Nasya drops for headache relief, clear respiratory tract & sharp senses.',
    ingredients: ['Jivanti', 'Devadaru', 'Cinnamon', 'Sesame Oil'],
  },
  {
    id: 'prod_28',
    title: 'Kshirabala 101 Times Refined Drops',
    subtitle: 'Neural Relaxation Oil',
    category: 'Wellness Oils',
    size: '30 ml',
    price: 799,
    originalPrice: 999,
    rating: 4.9,
    reviewCount: 175,
    badge: 'PREMIUM',
    inStock: true,
    stockQuantity: 55,
    description: 'Potent 101-processed sesame & milk oil for sleep disorders & nerve wellness.',
    ingredients: ['Bala Root', 'Cow Milk', 'Sesame Oil'],
  },
  {
    id: 'prod_29',
    title: 'Murivenna Herbal Wound Relief Oil',
    subtitle: 'First Aid & Bruise Care',
    category: 'Wellness Oils',
    size: '100 ml',
    price: 379,
    originalPrice: 449,
    rating: 4.7,
    reviewCount: 145,
    badge: 'FIRST AID',
    inStock: true,
    stockQuantity: 110,
    description: 'Kerala Ayurvedic oil for fast healing of minor cuts, burns & swelling.',
    ingredients: ['Betel Leaf', 'Aloe Vera', 'Shallot', 'Coconut Oil'],
  },
  {
    id: 'prod_30',
    title: 'Gandha Thailam Bone Health Drops',
    subtitle: 'Bone Density & Ligament Repair',
    category: 'Wellness Oils',
    size: '30 ml',
    price: 649,
    originalPrice: 799,
    rating: 4.8,
    reviewCount: 130,
    badge: 'HERBAL',
    inStock: true,
    stockQuantity: 65,
    description: 'Traditional formula fortified with Sesame & Milk to support bone recovery.',
    ingredients: ['Sesame Seeds', 'Milk', 'Eladi Gana Herbs'],
  },

  // Malts & Churnas (31-40)
  {
    id: 'prod_31',
    title: 'Nari Sondarya Malt',
    subtitle: 'Women Health & Vitality Booster',
    category: 'Malts & Churnas',
    size: '400 g',
    price: 899,
    originalPrice: 1099,
    rating: 4.9,
    reviewCount: 680,
    badge: 'TOP RATED',
    inStock: true,
    stockQuantity: 150,
    description: 'Traditional Ayurvedic herbal paste crafted with Shatavari, Ashwagandha & Apple extract.',
    ingredients: ['Shatavari', 'Ashwagandha', 'Apple Extract', 'Gokhru', 'Lodhra'],
  },
  {
    id: 'prod_32',
    title: 'Bhupha Malt Digestive Paste',
    subtitle: 'Gut Balance & Appetite Elixir',
    category: 'Malts & Churnas',
    size: '400 g',
    price: 749,
    originalPrice: 899,
    rating: 4.8,
    reviewCount: 420,
    badge: 'BESTSELLER',
    inStock: true,
    stockQuantity: 130,
    description: 'Delicious malt packed with Triphala & Pomegranate for smooth daily digestion.',
    ingredients: ['Pomegranate Extract', 'Triphala', 'Ginger', 'Pippali'],
  },
  {
    id: 'prod_33',
    title: 'Brahmi Memory & Focus Churna',
    subtitle: 'Brain Tonic & Mind Calmer',
    category: 'Malts & Churnas',
    size: '250 g',
    price: 499,
    originalPrice: 599,
    rating: 4.8,
    reviewCount: 340,
    badge: 'ORGANIC',
    inStock: true,
    stockQuantity: 100,
    description: 'Pure Organic Brahmi powder for mental clarity, stress relief & restful sleep.',
    ingredients: ['Pure Organic Brahmi Powder', 'Shankhpushpi', 'Vacha'],
  },
  {
    id: 'prod_34',
    title: 'Ashwagandha Vitality Malt',
    subtitle: 'Strength & Stress Relief Paste',
    category: 'Malts & Churnas',
    size: '400 g',
    price: 849,
    originalPrice: 999,
    rating: 4.9,
    reviewCount: 510,
    badge: 'POPULAR',
    inStock: true,
    stockQuantity: 110,
    description: 'Power-packed malt paste made with organic Ashwagandha roots & Raw Honey.',
    ingredients: ['Ashwagandha', 'Kaunch Beej', 'Safed Musli', 'Raw Honey'],
  },
  {
    id: 'prod_35',
    title: 'Triphala Detox & Cleansing Churna',
    subtitle: '100% Organic Bowel Regulator',
    category: 'Malts & Churnas',
    size: '200 g',
    price: 299,
    originalPrice: 399,
    rating: 4.9,
    reviewCount: 790,
    badge: 'ESSENTIAL',
    inStock: true,
    stockQuantity: 250,
    description: 'Balanced ratio of Amla, Haritaki & Bibhitaki for colon cleansing.',
    ingredients: ['Amla', 'Haritaki', 'Bibhitaki'],
  },
  {
    id: 'prod_36',
    title: 'Shatavari Hormonal Balance Churna',
    subtitle: 'Pure Female Wellness Powder',
    category: 'Malts & Churnas',
    size: '200 g',
    price: 399,
    originalPrice: 499,
    rating: 4.8,
    reviewCount: 270,
    badge: 'PURE',
    inStock: true,
    stockQuantity: 140,
    description: 'Root powder of Shatavari to support female endocrine balance & vitality.',
    ingredients: ['100% Pure Organic Shatavari Powder'],
  },
  {
    id: 'prod_37',
    title: 'Chyawanprash Special Herbal Malt',
    subtitle: 'Immunity & Seasonal Defense',
    category: 'Malts & Churnas',
    size: '500 g',
    price: 699,
    originalPrice: 849,
    rating: 4.9,
    reviewCount: 620,
    badge: 'BESTSELLER',
    inStock: true,
    stockQuantity: 160,
    description: 'Authentic 40-herb Chyawanprash prepared with fresh organic Amla & A2 Ghee.',
    ingredients: ['Fresh Amla', 'A2 Desi Ghee', 'Saffron', 'Pippali', 'Honey'],
  },
  {
    id: 'prod_38',
    title: 'Moringa Superfood Leaf Powder',
    subtitle: 'Nutrient Rich Green Churna',
    category: 'Malts & Churnas',
    size: '200 g',
    price: 349,
    originalPrice: 449,
    rating: 4.7,
    reviewCount: 220,
    badge: 'SUPERFOOD',
    inStock: true,
    stockQuantity: 180,
    description: 'Shade-dried drumstick leaf powder packed with Iron, Calcium & Amino Acids.',
    ingredients: ['100% Organic Dried Moringa Leaves'],
  },
  {
    id: 'prod_39',
    title: 'Amrutam Ortho Joint Pain Malt',
    subtitle: 'Nourishing Cartilage & Bone Paste',
    category: 'Malts & Churnas',
    size: '400 g',
    price: 899,
    originalPrice: 1099,
    rating: 4.8,
    reviewCount: 310,
    badge: 'SPECIALITY',
    inStock: true,
    stockQuantity: 90,
    description: 'Ayurvedic herbal malt infused with Hadjod & Guggulu for joint strength.',
    ingredients: ['Hadjod', 'Guggulu', 'Rasna', 'Shallaki', 'Honey'],
  },
  {
    id: 'prod_40',
    title: 'Karela & Jamun Sugar Balance Churna',
    subtitle: 'Metabolic & Glycemic Support',
    category: 'Malts & Churnas',
    size: '250 g',
    price: 379,
    originalPrice: 479,
    rating: 4.6,
    reviewCount: 250,
    badge: 'NATURAL',
    inStock: true,
    stockQuantity: 120,
    description: 'Synergistic mix of Bitter Gourd, Jamun seeds & Methi to maintain blood sugar.',
    ingredients: ['Karela Powder', 'Jamun Seed Powder', 'Gurmar', 'Methi'],
  },

  // Digestive Care (41-50)
  {
    id: 'prod_41',
    title: 'Hingwashtak Churna Powder',
    subtitle: 'Instant Gas & Flatulence Ease',
    category: 'Digestive',
    size: '100 g',
    price: 249,
    originalPrice: 299,
    rating: 4.9,
    reviewCount: 450,
    badge: 'FAST RELIEF',
    inStock: true,
    stockQuantity: 210,
    description: 'Traditional Asafoetida & Rock Salt powder for instant bloating relief.',
    ingredients: ['Shuddha Hing (Asafoetida)', 'Trikatu', 'Ajwain', 'Saindhava Salt'],
  },
  {
    id: 'prod_42',
    title: 'Avipattikar Churna for Acidity',
    subtitle: 'Pitta Pacifying Anti-Acid Powder',
    category: 'Digestive',
    size: '150 g',
    price: 299,
    originalPrice: 349,
    rating: 4.8,
    reviewCount: 390,
    badge: 'BESTSELLER',
    inStock: true,
    stockQuantity: 190,
    description: 'Classical Ayurvedic remedy for heartburn, GERD & hyperacidity.',
    ingredients: ['Amla', 'Haritaki', 'Cardamom', 'Clove', 'Nishoth'],
  },
  {
    id: 'prod_43',
    title: 'Ayush Kwath Kadha Drops',
    subtitle: 'Immunity & Throat Care Liquid',
    category: 'Digestive',
    size: '50 ml',
    price: 329,
    originalPrice: 399,
    rating: 4.8,
    reviewCount: 320,
    badge: 'CONCENTRATED',
    inStock: true,
    stockQuantity: 160,
    description: 'Tulsi, Cinnamon, Sunthi & Black Pepper liquid extract drops for immunity.',
    ingredients: ['Tulsi', 'Dalchini', 'Sunthi (Ginger)', 'Krishna Marich'],
  },
  {
    id: 'prod_44',
    title: 'Jeerakadyarishta Herbal Elixir',
    subtitle: 'Post-Meal Digestive Ferment',
    category: 'Digestive',
    size: '450 ml',
    price: 449,
    originalPrice: 549,
    rating: 4.7,
    reviewCount: 210,
    badge: 'TRADITIONAL',
    inStock: true,
    stockQuantity: 110,
    description: 'Cumin-infused traditional Arishta that improves assimilation & metabolic fire.',
    ingredients: ['Cumin Seeds', 'Jaggery', 'Dhataki Flowers', 'Ginger'],
  },
  {
    id: 'prod_45',
    title: 'Shankha Vati Digestive Tablets',
    subtitle: 'Abdominal Cramp & Indigestion Ease',
    category: 'Digestive',
    size: '60 Tabs',
    price: 349,
    originalPrice: 429,
    rating: 4.8,
    reviewCount: 180,
    badge: 'EFFECTIVE',
    inStock: true,
    stockQuantity: 140,
    description: 'Conch shell ash & Black salt tablets for heavy meal digestive support.',
    ingredients: ['Shankha Bhasma', 'Hing', 'Black Salt', 'Lemon Juice'],
  },
  {
    id: 'prod_46',
    title: 'Aloe Vera & Wheatgrass Detox Juice',
    subtitle: 'Pulp Rich Cleanse Drink',
    category: 'Digestive',
    size: '1000 ml',
    price: 499,
    originalPrice: 649,
    rating: 4.8,
    reviewCount: 410,
    badge: 'VALUE PACK',
    inStock: true,
    stockQuantity: 120,
    description: 'Cold-pressed organic Aloe Vera leaf pulp juice for gut lining repair.',
    ingredients: ['Organic Aloe Vera Inner Leaf Pulp', 'Wheatgrass Juice'],
  },
  {
    id: 'prod_47',
    title: 'Amla & Giloy Digestive Syrup',
    subtitle: 'Liver Detox & Blood Purifier',
    category: 'Digestive',
    size: '500 ml',
    price: 399,
    originalPrice: 499,
    rating: 4.9,
    reviewCount: 360,
    badge: 'POPULAR',
    inStock: true,
    stockQuantity: 150,
    description: 'Dual detox formula combining vitamin-rich Amla with Giloy (Guduchi).',
    ingredients: ['Fresh Amla Juice', 'Giloy Stem Juice', 'Holy Basil'],
  },
  {
    id: 'prod_48',
    title: 'Lavan Bhaskar Churna Salt',
    subtitle: 'Appetizer & Taste Restorer',
    category: 'Digestive',
    size: '100 g',
    price: 199,
    originalPrice: 249,
    rating: 4.7,
    reviewCount: 280,
    badge: 'CLASSIC',
    inStock: true,
    stockQuantity: 220,
    description: 'Spiced rock salt mix that stimulates salivary glands & digestive juices.',
    ingredients: ['Saindhava Salt', 'Sea Salt', 'Black Pepper', 'Pippali'],
  },
  {
    id: 'prod_49',
    title: 'Drakshashta Herbal Stomach Syrup',
    subtitle: 'Gentle Laxative & Refreshing Drink',
    category: 'Digestive',
    size: '450 ml',
    price: 429,
    originalPrice: 529,
    rating: 4.8,
    reviewCount: 195,
    badge: 'GENTLE',
    inStock: true,
    stockQuantity: 100,
    description: 'Raisin & Nutmeg herbal liquid to soothe stomach lining & ease constipation.',
    ingredients: ['Black Raisins (Draksha)', 'Jaggery', 'Nutmeg', 'Cinnamon'],
  },
  {
    id: 'prod_50',
    title: 'Triphala & Ginger Digestive Effervescent',
    subtitle: 'Instant Fizzy Gut Drink',
    category: 'Digestive',
    size: '20 Tabs',
    price: 399,
    originalPrice: 499,
    rating: 4.9,
    reviewCount: 330,
    badge: 'MODERN AYURVEDA',
    inStock: true,
    stockQuantity: 165,
    description: 'Effervescent tablets that dissolve in water for a refreshing Ayurvedic gut drink.',
    ingredients: ['Triphala Extract', 'Ginger Extract', 'Rock Salt', 'Citric Acid'],
  },
];

async function seedProducts() {
  try {
    console.log('⏳ Connecting to MongoDB Database...');
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB successfully.');

    console.log('🗑️ Clearing existing products collection...');
    await Product.deleteMany({});

    console.log(`📦 Inserting ${PRODUCTS_50.length} authentic Amrutam Ayurvedic products...`);
    const inserted = await Product.insertMany(PRODUCTS_50);

    console.log(`🎉 SUCCESS! Successfully seeded ${inserted.length} products into MongoDB!`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding products into MongoDB:', error);
    process.exit(1);
  }
}

seedProducts();
